version: '3.8'

services:
  backend:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: school_event_backend
    ports:
      - "8000:8000"
    environment:
      - ADMIN_PASSWORD=adminPass
      - SECRET_KEY=MySecretKeyForSessions
      - CSRF_SECRET=AnotherSecretKeyForCSRF
      - DB_PATH=/app/data/db1.db
    volumes:
      - ./data:/app/data
    restart: unless-stopped
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: school_event_nginx
    ports:
      - "80:80"
    volumes:
      - ./app/nginx.conf:/etc/nginx/conf.d/default.conf:ro
      - ./app/backend/static:/usr/share/nginx/html/static:ro
      - ./app/backend/images:/usr/share/nginx/html/images:ro
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - app_network

networks:
  app_network:
    driver: bridge
